// apps/frontend/src/components/buttons/AccrueButton.tsx
import { TRS } from '#/config/smart-contracts/TRS/TRS'
import { useWaitForTransactionReceipt, useWriteContract } from 'wagmi'

interface AccrueButtonProps {
  tokenId: string
  className: string
  innerText: string
}
export function AccrueButton({
  tokenId,
  className,
  innerText,
}: AccrueButtonProps) {
  const { mutateAsync, isPending, data: txHash } = useWriteContract()

  const accrueRevenue = async () => {
    await mutateAsync({
      ...TRS,
      functionName: 'accrueRevenue',
      args: [BigInt(tokenId)],
    })
  }

  const { isLoading: isConfirming } = useWaitForTransactionReceipt({
    hash: txHash,
  })
  return (
    <button
      disabled={isPending || isConfirming}
      onClick={async (e) => {
        e.stopPropagation()
        e.preventDefault()
        await accrueRevenue()
      }}
      className={className}
    >
      {innerText}
    </button>
  )
}

// src/components/buttons/AccrueButton.vue
<script lang="ts" setup>
import { M3TRS } from '@/config/smart-contracts/M3TRS'
import { useWaitForTransactionReceipt, useWriteContract } from '@wagmi/vue'
const props = defineProps(['tokenId', 'class', 'innerText'])
const { mutateAsync, isPending, data: txHash } = useWriteContract()

const accrueRevenue = async () => {
  await mutateAsync({
    ...M3TRS,
    functionName: 'accrueRevenue',
    args: [BigInt(props.tokenId)],
  })
}

const {
  isLoading: isConfirming,
  //isSuccess: isConfirmed
} = useWaitForTransactionReceipt({
  hash: txHash,
})
</script>
<template>
  <button :disabled="isPending || isConfirming" @click="accrueRevenue" :class="props.class">
    {{ innerText }}
  </button>
</template>
