// apps/frontend/src/components/buttons/CollectButton.tsx
import { TRS } from '@/config/smart-contracts/TRS/TRS'
import { useWaitForTransactionReceipt, useWriteContract } from 'wagmi'

interface CollectButtonProps {
  tokenId: bigint
  innerText: string
  className: string
}

export function CollectButton({
  tokenId,
  innerText,
  className,
}: CollectButtonProps) {
  const { mutateAsync, isPending, data: txHash } = useWriteContract()

  const collectRevenue = async () => {
    await mutateAsync({
      ...TRS,
      functionName: 'collectRevenue',
      args: [tokenId],
    })
  }

  const {
    isLoading: isConfirming,
    // isSuccess: isConfirmed
  } = useWaitForTransactionReceipt({
    hash: txHash,
  })

  return (
    <button
      onClick={async (e) => {
        e.stopPropagation()
        e.preventDefault()
        await collectRevenue()
      }}
      disabled={isPending || isConfirming}
      className={className}
    >
      {innerText}
    </button>
  )
}

// apps/frontend/src/components/buttons/CollectButton.vue
<script lang="ts" setup>
import { TRS } from "@/config/smart-contracts/TRS/TRS";
import { useWaitForTransactionReceipt, useWriteContract } from "@wagmi/vue";
const props = defineProps(["tokenId", "class", "innerText"]);
const { mutateAsync, isPending, data: txHash } = useWriteContract();

const collectRevenue = async () => {
  await mutateAsync({
    ...TRS,
    functionName: "collectRevenue",
    args: [BigInt(props.tokenId)],
  });
};

const {
  isLoading: isConfirming,
  // isSuccess: isConfirmed
} = useWaitForTransactionReceipt({
  hash: txHash,
});
</script>
<template>
  <button @click.stop="collectRevenue" :disabled="isPending || isConfirming" :class="props.class">
    {{ innerText }}
  </button>
</template>
